[features]
seeds = false
[programs.localnet]
post = "7TqUKeDRtCKTpsr7TAAvXwQicDcT8y1eVaLzyAfHLHLL"
comment = "2BqbRJMk2CPseUTzGJcQHbKrsyR3wVFZT1NEWCCUNv5d"
user = "7HaWRPy31cXVPVWcWXEpiRiPKBNXrQhaNd4uKsMp7j3C"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/aland/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
